/**
 * @fileoverview Domain service for validating and exposing CLI/Proxy settings.
 *
 * Exports:
 * - ProxySettingsService - Validates updates and builds env preview payload.
 */

import { BadRequestException, Injectable } from "@nestjs/common";
import * as fs from "node:fs/promises";
import * as path from "node:path";

import { ProxySettingsStore } from "./proxy-settings.store";
import { DockerComposeService } from "../projects/docker-compose.service";
import { ProxyApplyResult, ProxySettingsInput, ProxySettingsSnapshot } from "./proxy-settings.types";

const URL_PROTOCOL_SEPARATOR = "://";
const RUNTIME_CONFIG_DIR_ENV = "RUNTIME_CONFIG_DIR";
const VLESS_OVERRIDE_FILE = "docker-compose.vless.yml";
const PRIMARY_COMPOSE_FILE = "docker-compose.yml";
const ENV_FILE = ".env";
const VLESS_PROXY_ENV_FILE = path.join("infra", "vless", "proxy.env");

const DIRECT_OVERRIDE_CONTENT = `services: {}\n`;

const VLESS_OVERRIDE_CONTENT = `x-logging-defaults: &logging_defaults
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  vless-proxy:
    image: ghcr.io/xtls/xray-core:latest
    command: ["run", "-c", "/etc/xray/config.json"]
    volumes:
      - ./infra/vless/xray.json:/etc/xray/config.json:ro
    networks:
      - ai_proxy
    logging: *logging_defaults
    restart: unless-stopped

  bot:
    # Route bot external AI calls through VLESS while keeping internal calls direct.
    env_file:
      - ./infra/vless/proxy.env
    depends_on:
      - vless-proxy
    networks:
      - ai_proxy

  cliproxy:
    # Route CLIProxy external provider traffic through VLESS.
    env_file:
      - ./infra/vless/proxy.env
    depends_on:
      - vless-proxy
    networks:
      - ai_proxy

networks:
  ai_proxy:
    driver: bridge
`;

@Injectable()
export class ProxySettingsService {
  public constructor(
    private readonly store: ProxySettingsStore,
    private readonly dockerCompose: DockerComposeService
  ) {}

  public async getSettings(): Promise<ProxySettingsSnapshot> {
    /* Expose current profile together with env values expected by runtime services. */
    const record = await this.store.get();
    await this.syncRuntimeFiles(record.mode, record.vlessProxyUrl, record.noProxy);
    return {
      ...record,
      envPreview: this.toEnvPreview(record.mode, record.vlessProxyUrl, record.noProxy),
      runtimeFiles: this.getRuntimeFilesMeta()
    };
  }

  public async updateSettings(input: ProxySettingsInput): Promise<ProxySettingsSnapshot> {
    /* Enforce explicit invariants so Mini App cannot persist ambiguous proxy state. */
    const normalized = this.normalizeInput(input);
    this.assertInput(normalized);

    const saved = await this.store.set(normalized);
    await this.syncRuntimeFiles(saved.mode, saved.vlessProxyUrl, saved.noProxy);
    return {
      ...saved,
      envPreview: this.toEnvPreview(saved.mode, saved.vlessProxyUrl, saved.noProxy),
      runtimeFiles: this.getRuntimeFilesMeta()
    };
  }

  public async applyRuntimeStack(): Promise<ProxyApplyResult> {
    /* Run docker compose with generated override in runtime directory configured for backend. */
    const runtimeConfigDir = this.requireRuntimeConfigDir();
    const args = [
      "--env-file",
      ENV_FILE,
      "-f",
      PRIMARY_COMPOSE_FILE,
      "-f",
      VLESS_OVERRIDE_FILE,
      "up",
      "-d"
    ];
    const result = await this.dockerCompose.run(args, runtimeConfigDir);
    return {
      ok: true,
      command: this.toApplyCommand(),
      stdout: result.stdout,
      stderr: result.stderr
    };
  }

  private async syncRuntimeFiles(mode: "direct" | "vless", vlessProxyUrl: string | null, noProxy: string): Promise<void> {
    /* Persist generated runtime override/env files when backend has runtime config mount. */
    const runtimeConfigDir = process.env[RUNTIME_CONFIG_DIR_ENV]?.trim() || "";
    if (!runtimeConfigDir) {
      return;
    }

    const overridePath = path.join(runtimeConfigDir, VLESS_OVERRIDE_FILE);
    const proxyEnvPath = path.join(runtimeConfigDir, VLESS_PROXY_ENV_FILE);

    await fs.mkdir(path.dirname(proxyEnvPath), { recursive: true });
    await fs.writeFile(proxyEnvPath, this.renderProxyEnv(mode, vlessProxyUrl, noProxy), "utf-8");

    const overrideContent = mode === "vless" ? VLESS_OVERRIDE_CONTENT : DIRECT_OVERRIDE_CONTENT;
    await fs.writeFile(overridePath, overrideContent, "utf-8");
  }

  private renderProxyEnv(mode: "direct" | "vless", vlessProxyUrl: string | null, noProxy: string): string {
    /* Generate deterministic env file consumed by bot/cliproxy override env_file. */
    const proxyValue = mode === "vless" ? vlessProxyUrl ?? "" : "";
    return [
      "# Generated by Remote Vibe Station Mini App (CLI/Proxy tab)",
      `HTTP_PROXY=${proxyValue}`,
      `HTTPS_PROXY=${proxyValue}`,
      `ALL_PROXY=${proxyValue}`,
      `NO_PROXY=${noProxy}`,
      ""
    ].join("\n");
  }

  private getRuntimeFilesMeta() {
    /* Expose generated file paths and apply command to simplify operator workflow. */
    const runtimeConfigDir = process.env[RUNTIME_CONFIG_DIR_ENV]?.trim() || null;
    if (!runtimeConfigDir) {
      return {
        runtimeConfigDir: null,
        proxyEnvPath: null,
        overridePath: null,
        recommendedApplyCommand: null
      };
    }

    const proxyEnvPath = path.join(runtimeConfigDir, VLESS_PROXY_ENV_FILE);
    const overridePath = path.join(runtimeConfigDir, VLESS_OVERRIDE_FILE);
    return {
      runtimeConfigDir,
      proxyEnvPath,
      overridePath,
      recommendedApplyCommand: this.toApplyCommand()
    };
  }

  private toApplyCommand(): string {
    /* Keep one canonical compose command string for API/UI to avoid mismatch. */
    return `docker compose --env-file ${ENV_FILE} -f ${PRIMARY_COMPOSE_FILE} -f ${VLESS_OVERRIDE_FILE} up -d`;
  }

  private requireRuntimeConfigDir(): string {
    /* Applying runtime stack requires mounted runtime config directory. */
    const runtimeConfigDir = process.env[RUNTIME_CONFIG_DIR_ENV]?.trim() || "";
    if (!runtimeConfigDir) {
      throw new BadRequestException("RUNTIME_CONFIG_DIR is not configured in backend container");
    }
    return runtimeConfigDir;
  }

  private normalizeInput(input: ProxySettingsInput): ProxySettingsInput {
    /* Trim incoming strings to keep persisted profile canonical and diff-friendly. */
    return {
      mode: input.mode,
      vlessProxyUrl:
        typeof input.vlessProxyUrl === "string" && input.vlessProxyUrl.trim().length > 0
          ? input.vlessProxyUrl.trim()
          : null,
      noProxy:
        typeof input.noProxy === "string" && input.noProxy.trim().length > 0 ? input.noProxy.trim() : ""
    };
  }

  private assertInput(input: ProxySettingsInput): void {
    /* VLESS mode requires explicit proxy URL, direct mode forbids stale URL values. */
    if (input.mode === "vless") {
      if (!input.vlessProxyUrl) {
        throw new BadRequestException("vlessProxyUrl is required for vless mode");
      }

      if (!this.isProxyUrl(input.vlessProxyUrl)) {
        throw new BadRequestException("vlessProxyUrl must include protocol (socks5/http/https)");
      }
    }

    if (input.mode === "direct" && input.vlessProxyUrl) {
      throw new BadRequestException("vlessProxyUrl must be empty in direct mode");
    }

    if (!input.noProxy) {
      throw new BadRequestException("noProxy is required");
    }
  }

  private isProxyUrl(value: string): boolean {
    /* Keep validation strict enough for runtime env export but still protocol-agnostic. */
    if (!value.includes(URL_PROTOCOL_SEPARATOR)) {
      return false;
    }

    return /^socks5h?:\/\//i.test(value) || /^https?:\/\//i.test(value);
  }

  private toEnvPreview(mode: "direct" | "vless", vlessProxyUrl: string | null, noProxy: string) {
    /* Build env snapshot consumed by bot/cliproxy when proxy mode is enabled. */
    if (mode === "direct") {
      return {
        HTTP_PROXY: null,
        HTTPS_PROXY: null,
        ALL_PROXY: null,
        NO_PROXY: noProxy
      };
    }

    return {
      HTTP_PROXY: vlessProxyUrl,
      HTTPS_PROXY: vlessProxyUrl,
      ALL_PROXY: vlessProxyUrl,
      NO_PROXY: noProxy
    };
  }
}
